PRODUCT_PACKAGES += \
	HardwareOverlayPicker \
	QtiAudio \
	TrebleApp \
	treble-overlay-NavBar \
	treble-overlay-NightMode \
	treble-overlay-SystemUI-FalseLocks \
	treble-overlay-Telephony-LTE \
	treble-overlay-asus-zenfone5 \
	treble-overlay-asus-zenfone5z \
	treble-overlay-asus-zenfonelivel1za550kl \
	treble-overlay-asus-zenfonemaxm2 \
	treble-overlay-bq-jeice \
	treble-overlay-caf-ims \
	treble-overlay-devinputjack \
	treble-overlay-duoqin-qin2pro \
	treble-overlay-essential-ph_1 \
	treble-overlay-gestures \
	treble-overlay-htc-exodus1 \
	treble-overlay-htc-u12plus \
	treble-overlay-huawei \
	treble-overlay-huawei-ANE \
	treble-overlay-huawei-ARE \
	treble-overlay-huawei-ATU \
	treble-overlay-huawei-AUM \
	treble-overlay-huawei-BKL \
	treble-overlay-huawei-BND \
	treble-overlay-huawei-CLT \
	treble-overlay-huawei-DUK \
	treble-overlay-huawei-EML \
	treble-overlay-huawei-LLD \
	treble-overlay-huawei-PIC \
	treble-overlay-huawei-PRA \
	treble-overlay-huawei-RNE \
	treble-overlay-huawei-STF \
	treble-overlay-huawei-VTR \
	treble-overlay-huawei-WAS \
	treble-overlay-hw-ims \
	treble-overlay-infinix-note5 \
	treble-overlay-infinix-s4 \
	treble-overlay-infinix-zero6 \
	treble-overlay-lenovo-k5pro \
	treble-overlay-lenovo-s5 \
	treble-overlay-lenovo-z5 \
	treble-overlay-lg-g7 \
	treble-overlay-lg-v40 \
	treble-overlay-moto-e5 \
	treble-overlay-moto-e5plus \
	treble-overlay-moto-g6 \
	treble-overlay-moto-g6play \
	treble-overlay-moto-g6plus \
	treble-overlay-moto-g7play \
	treble-overlay-moto-g7power \
	treble-overlay-moto-one \
	treble-overlay-moto-one-action \
	treble-overlay-mtk-ims \
	treble-overlay-nokia-b2n-7plus \
	treble-overlay-nokia-ctl-7-1 \
	treble-overlay-nokia-drg-6.1plus-x6 \
	treble-overlay-nokia-nokia_4_2 \
	treble-overlay-nokia-pl2-6.1 \
	treble-overlay-nokia-pnx-8.1-x7 \
	treble-overlay-nokia-pnx-8.1-x7-systemui \
	treble-overlay-nubia-z18mini \
	treble-overlay-oneplus-op6 \
	treble-overlay-oneplus-op6t \
	treble-overlay-oneplus-op6t-systemui \
	treble-overlay-razer-cheryl \
	treble-overlay-realme-x2pro \
	treble-overlay-samsung-S10pq \
	treble-overlay-samsung-S10q \
	treble-overlay-samsung-a30 \
	treble-overlay-samsung-a40 \
	treble-overlay-samsung-a50 \
	treble-overlay-samsung-a51x \
	treble-overlay-samsung-a60q \
	treble-overlay-samsung-gta3xl \
	treble-overlay-samsung-s10e \
	treble-overlay-samsung-s9-systemui \
	treble-overlay-sec-ims \
	treble-overlay-sharp-s2 \
	treble-overlay-sony-XZ3 \
	treble-overlay-teclast-m30 \
	treble-overlay-tecno-camon11 \
	treble-overlay-umidigi-power \
	treble-overlay-webview \
	treble-overlay-wifi5g \
	treble-overlay-xiaomi-mi6x \
	treble-overlay-xiaomi-mi8 \
	treble-overlay-xiaomi-mi8ee \
	treble-overlay-xiaomi-mi8lite \
	treble-overlay-xiaomi-mi8pro \
	treble-overlay-xiaomi-mi8se \
	treble-overlay-xiaomi-mi9 \
	treble-overlay-xiaomi-mi9se \
	treble-overlay-xiaomi-mia2 \
	treble-overlay-xiaomi-mia2lite \
	treble-overlay-xiaomi-mimax3 \
	treble-overlay-xiaomi-mimix2s \
	treble-overlay-xiaomi-mimix3 \
	treble-overlay-xiaomi-mimix3-systemui \
	treble-overlay-xiaomi-mipad4 \
	treble-overlay-xiaomi-miplay \
	treble-overlay-xiaomi-pocof1 \
	treble-overlay-xiaomi-redmi6 \
	treble-overlay-xiaomi-redmi6a \
	treble-overlay-xiaomi-redmi6pro \
	treble-overlay-xiaomi-redmi7a \
	treble-overlay-xiaomi-redmi7onc \
	treble-overlay-xiaomi-redmi8a \
	treble-overlay-xiaomi-redmigo \
	treble-overlay-xiaomi-redmik20pro \
	treble-overlay-xiaomi-redminote5 \
	treble-overlay-xiaomi-redminote6pro \
	treble-overlay-xiaomi-redminote6pro-systemui \
	treble-overlay-xiaomi-redminote7 \
	treble-overlay-xiaomi-redminote8pro \
	treble-overlay-xiaomi-redmis2 \

