#!/system/bin/sh

set -x

#Do this only on devices with huawei fingerprint HAL
grep -qF vendor.huawei.hardware.biometrics.fingerprint /vendor/manifest.xml || exit 0

#Ask fingerprint hardware service to enable navigation
CLASSPATH=/system/phh/hw-fpnav.dex \
	/system/bin/app_process \
		/data/local/tmp/ \
		Test
